service: sls-typescript-template

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  memorySize: 256
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  stage: ${env:NODE_ENV}
  
functions:
  hello:
    handler: dist/src/handlers/index.hello
    events:
      - http:
          method: GET
          path: /hello

plugins:
  - serverless-offline
