name: Serverless workflow

on: ['push']

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Run coverage
        run: |
          yarn coverage
  
  deploy:
    if: github.ref == 'refs/heads/main'
      environment: main
    if: github.ref == 'refs/heads/staging'
      environment: staging

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install development dependencies
        run: |
          yarn install:development

      - name: Build application
        run: |
          yarn build

      - name: Remove local plugins
        run: |
          yq eval -i 'del(.plugins)' serverless.yml

      - name: Install production dependencies
        run: |
          yarn install:production

      - name: Create env file # Environment secrets
        run: |
          touch .env
          echo NODE_ENV=${{secrets.NODE_ENV}} >> .env

      - name: Serverless deploy
        uses: serverless/github-action@v2
        with:
          args: deploy
        env: # Repository secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
